name: ✨ Feature Request
description: 새로운 기능이나 개선사항을 제안해주세요
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        새로운 기능이나 개선사항을 제안해 주셔서 감사합니다!
        IT 자산 관리 시스템을 더 좋게 만드는 데 도움이 됩니다.

  - type: textarea
    id: problem-description
    attributes:
      label: 🤔 해결하고자 하는 문제
      description: 현재 어떤 문제나 불편함이 있나요?
      placeholder: 예) 현재 하드웨어 검색 시 브랜드별로 필터링할 수 없어서 찾기가 어렵습니다.
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: 💡 제안하는 해결책
      description: 어떤 기능이나 개선사항을 원하시나요?
      placeholder: |
        예) 하드웨어 관리 페이지에 다음 필터 옵션들을 추가했으면 좋겠습니다:
        - 브랜드별 필터 (삼성, LG, HP 등)
        - 타입별 필터 (노트북, 데스크탑, 모니터 등)
        - 상태별 필터 (사용중, 대기중, 수리중 등)
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: 📂 기능 카테고리
      description: 이 기능 요청은 어떤 영역과 관련이 있나요?
      options:
        - "임직원 관리"
        - "하드웨어 자산 관리"
        - "소프트웨어 인벤토리"
        - "자산 할당/반납"
        - "Excel 내보내기"
        - "대시보드/통계"
        - "사용자 인터페이스"
        - "보안/인증"
        - "Docker/배포"
        - "API/백엔드"
        - "기타"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: ⭐ 우선순위
      description: 이 기능이 얼마나 중요하다고 생각하시나요?
      options:
        - "높음 (업무에 필수적)"
        - "보통 (업무 효율성 향상)"
        - "낮음 (있으면 좋은 기능)"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 고려해본 대안
      description: 현재 이 문제를 해결하기 위해 어떤 방법을 사용하고 있나요?
      placeholder: 예) 현재는 Excel로 내보낸 후 수동으로 필터링하고 있습니다.

  - type: textarea
    id: mockup-description
    attributes:
      label: 🎨 UI/UX 아이디어
      description: UI나 사용자 경험에 대한 구체적인 아이디어가 있다면 설명해주세요.
      placeholder: |
        예) 하드웨어 목록 상단에 필터 바를 추가하여:
        - 드롭다운으로 브랜드 선택
        - 체크박스로 타입 다중 선택
        - 검색창에 모델명 입력 가능

  - type: textarea
    id: use-cases
    attributes:
      label: 🎯 사용 사례
      description: 이 기능이 추가되면 어떤 상황에서 어떻게 사용할 계획인가요?
      placeholder: |
        예)
        1. 월말 자산 현황 보고서 작성 시 브랜드별 통계 산출
        2. 특정 모델 노트북의 재고 확인
        3. 수리중인 장비만 모아서 현황 파악

  - type: input
    id: affected-users
    attributes:
      label: 👥 영향받을 사용자 수
      description: 이 기능으로 혜택을 받을 것으로 예상되는 사용자는 몇 명 정도인가요?
      placeholder: 예) 약 15명 (전체 IT 관리 담당자)

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 추가 정보
      description: 관련 스크린샷, 참고 링크, 또는 기타 유용한 정보가 있다면 첨부해주세요.

  - type: checkboxes
    id: contribution
    attributes:
      label: 기여 의향
      description: 이 기능 개발에 어떤 방식으로 기여할 수 있나요?
      options:
        - label: 테스트에 참여할 수 있습니다
        - label: UI/UX 디자인을 도울 수 있습니다
        - label: 기능 요구사항 정의를 도울 수 있습니다
        - label: 코드 개발에 참여할 수 있습니다
        - label: 문서화 작업을 도울 수 있습니다
